config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pets
  resources :users

  resources :toys





  patch '/toggle_hunger/:id', to: 'pets#pet_hungry', as: 'pet_hungry'


  root 'pets#index'


  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/login', to: 'sessions#delete', as: 'logout'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user

  has_many :toys




end

app/models/toy.rb
class Toy < ApplicationRecord
  belongs_to :pet
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :pets






  # def self.away?
  #   self.all.each do |person|
  #     if person.home == true
  #       person.home = false
  #     else
  #       person.home = true
  #     end
  #   end
  # end
  #
  # def self.most_pets
  #   @sort_pets = self.all.sort_by do |person|
  #     person.pets.length
  #
  #   end
  #   @sort_pets
  # end






end #end of class

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery unless: -> { request.format.json? }



  before_action :authorized
  helper_method :current_user

  def current_user
    User.find_by({id: session[:user_id]})
  end

  def logged_in?
    !!current_user
  end

  def authorized
    redirect_to login_path unless logged_in?
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  skip_before_action :authorized, only: [:new, :index, :show, :create]
  before_action :set_pet, only: [:show, :pet_hungry, :edit, :update, :destroy]
  helper_method :current_user


  def new
    @pet = Pet.new
    @users = User.all
    respond_to do |f|
      f.html {render :new}
      f.json {render json: @pet}
    end
  end

  def index
    @pets = Pet.all
    respond_to do |f|
      f.html {render :index}
      f.json {render json: @pets}
    end
  end

  def show
    @toy = @pet.toys.build
    respond_to do |f|
      f.html {render :show}
      f.json {render json: @pet}
    end
  end

  def pet_hungry
      @pet.toggle(:hungry)
      @pet.save
      respond_to do |f|
      f.html {redirect_to pet_path(@pet)}
      f.json {render json: @pet}
    end
  end


  def create
    @pet = Pet.create(pet_params)
    @users = User.all
    if @pet.valid?
      respond_to do |f|
        f.html {redirect_to pet_path(@pet)}
        f.json {render json: @pet}
      end
    else
      flash[:notice] = @pet.errors.full_messages.join
      render :new
    end
  end

  def edit
    @users = User.all
    respond_to do |f|
      f.html {render :edit}
      f.json {render json: @pet}
    end
  end

  def update
    @pet.update(pet_params)
    respond_to do |f|
      f.html {redirect_to pet_path(@pet)}
      f.json {render json: @pet}
    end
  end

  def destroy
    @pet.destroy
    respond_to do |f|
      f.html {redirect_to user_path(@pet.user)}
      f.json {render json: @pet}
    end
  end




  private

  def set_pet
    @pet = Pet.find(params[:id])
  end

  def pet_params
    params.require(:pet).permit(:name, :kind, :age, :user_id, :color, :hair, :image)
  end





end #end of class

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]
  helper_method :current_user

  def new
    render :new
  end

  # def create
  #   # // you need to receive user name & password from js
  #   # // through params
  #   @user = User.find_by(name: params[:name])
  #   if @user && @user.authenticate(params[:password])
  #     session[:user_id] = @user.id
  #     # # // serve up json
  #     # render json: @user
  #     render json: @user.pets
  #     # redirect_to user_path(@user)
  #   else
  #     flash[:message] = 'Invalid name or password'
  #     redirect_to login_path
  #   end
  # end




  def create
    # // you need to receive user name & password from js
    # // through params
    @user = User.find_by(name: params[:name])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id

      respond_to do |f|
        f.html {redirect_to user_path(@user)}
        # f.html {render :show}

        f.json {render json: @user.pets}
      # # // serve up json
      # render json: @user
      # render json: @user.pets
    end
      # redirect_to user_path(@user)
    else
      flash[:message] = 'Invalid name or password'
      redirect_to login_path
    end
  end






  def delete
    session.delete(:user_id)
    redirect_to '/'
  end


end

app/controllers/toys_controller.rb
class ToysController < ApplicationController

  def index
    @toys = Toy.all
    respond_to do |f|
      f.html {render :index}
      f.json {render json: @toys}
    end
  end

  def show
    @toy = Toy.find(params[:id])
    respond_to do |f|
      f.html {render :show}
      f.json {render json: @toy}
    end
  end


  private

  def toy_params
    params.require(:toy).permit(:name, :pet_id, :user_id)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]
  before_action :set_user, only: [:show, :destroy]
  helper_method :current_user


  def new
    @user = User.new
    respond_to do |f|
      f.html {render :new}
      f.json {render json: @user}
    end
  end

  

  def index
    @users = User.all
    respond_to do |f|
      f.html {render :index}
      f.json {render json: @users}
    end
  end

  def show
    @pet = @user.pets.build
    # @pet = @user.pets.build
    respond_to do |f|
      f.html {render :show}
      f.json {render json: @user}
    end
    # render json: @user
  end

  # def pet_attribute
  #   Self.object.pet.attribute
  # end

  def destroy
    @user.destroy
  end

  def create
    @user = User.new(user_params)

    if(@user.save)
      session[:user_id] = @user.id
      render json: @user

    else
      flash[:notice] = @user.errors.full_messages.join
      redirect_to new_user_path
    end
  end


  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :password)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/toys_helper.rb
module ToysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdoptPet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Compiled and minified CSS -->
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC|Zilla+Slab&display=swap" rel="stylesheet">
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"> -->
    <title>Adopt a Pet</title>
  </head>

  <body>

    <div id="navbar">
      <ul>
        <div class='log_in'>
        <li><%= link_to 'home', root_path %></li>
        <li><%= link_to 'log in', login_path %></li>
        <li><%= link_to 'sign up', new_user_path %></li>
        <li><%= link_to 'log out', logout_path %></li>
        </div>
      </ul>
    </div>



      <div id="container" >









          <%= yield %>


      </div>

  </body>
</html>

app/views/pets/_form.erb
<div id="pet-form">

<% if flash[:notice] %>
<%= flash[:notice] %>
<% end %>

<%= form_for @pet do |f| %>
<%= f.label :name %>
<%= f.text_field :name %><br><br>
<%= f.label :kind %>
<%= f.text_field :kind %><br><br>
<%= f.label :age %>
<%= f.number_field :age %><br><br>
<%= f.label :color %>
<%= f.text_field :color %><br><br>
<%= f.label :hair %>
<%= f.text_field :hair %><br><br>
<%= f.label :your_name %>
<%= f.collection_select :user_id, @users, :id, :name %><br><br>
<%= f.submit%>
<% end %>

</div>

app/views/pets/edit.erb
<h3>Edit your pet!</h3>

<%= render :partial => 'form' %>

app/views/pets/index.erb
<div id="pets-container">




  </div>

app/views/pets/new.erb
<h3>Adopt a pet!</h3>


<%= render :partial => 'form'%>

app/views/pets/park.erb
<h3>pet the pet</h3>

hi! my name is:
<%= @pet.name %><br>
i'm a:
<%= @pet.kind %><br>
i'm
<%= @pet.age %>
years old<br>
my fur color is:
<%= @pet.color %>
and my hair is:
<%= @pet.hair %><br><br>


<% if @pet.hungry %>
  i'm hungry!
  <%= button_to 'please feed me', pet_hungry_path(@pet), method: :patch, class: 'button'%><br>
  you just ate!<%= button_to 'time for play', user_path(@pet.user), method: :get, class: 'button' %><br><br>

<% else %>
  i'm stuffed.
  <%= button_to 'i`m hungry again', pet_hungry_path(@pet), method: :patch, class: 'button'%><br><br>
<% end %>
<% if !@pet.hungry %>
  <%= button_to 'time for a nap', user_path(@pet.user), method: :get, class: 'button' %><br><br>
<% end %>

<%= button_to 'pet needs changin?', edit_pet_path, method: :get, class: 'button' %><br><br>

<%= button_to 'pet went to heaven', pet_path, method: :delete, data: { confirm: 'are u sure?' }, class: 'button'%><br><br>


$('#pets-container').on('click', function(e) {
//     e.preventDefault()
//     let petId = e.target.dataset.id
//     let petShow = e.target.dataset.action === 'show-pet'
//     let getToys = e.target.dataset.action === 'get-toys'
//     if (e.target.dataset.action === 'show-pet') {
//       getSinglePet(petId, e.target)
//       console.log(petShow)
//     } else if (getToys) {
//       getPetToys(petId)
//     }
//   })

app/views/pets/show.erb
<div id="pets-containers">





  </div>

app/views/toys/index.erb
<%@toys.each do |toy| %>

<%= toy.name %>

<% end %>

app/views/users/index.erb
<div id='users-container'>
  </div>

app/views/users/new.erb
<div class="add_user_form" data-action='user-sign-up'>


  <h6>Sign up</h6>


  <%= form_for(@user) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.submit %>
    <% end %>

</div>

app/views/users/park.erb
<h2>hi, <%=@user.name%>!</h2>

<h3>your pets</h3>

<div id="my-pets">
  <ul>
    <li></li>

  </ul>





<% @user.pets.each do |pet|%>

name: <%= button_to pet.name, pet_path(pet), method: :get, class: 'button'%>
type of pet: <%= pet.kind%><br>


<% end %>


<%= button_to 'adopt a pet', new_pet_path, method: :get, class: 'button' %><br><br>

<%= button_to 'sign out', logout_path,  method: :get, data: { confirm: 'are u sure?' }, class: 'button' %><br><br>
</div>


$('#new_user').on('submit', function(e) {
  e.preventDefault()
  console.log('hiya')
  const values = $(this).serialize()
  const name = document.querySelector('#user_name').value
  const password = document.querySelector('#user_password').value
  console.log(name, password)
let dataObj = {name: name, password: password};
console.log(dataObj)
// fetch("http://localhost:3000/users", {
fetch("/users.json", {

method: 'POST',
body: JSON.stringify(dataObj),
headers:{
  'Content-Type': 'application/json'
}
})
  .then(res  => res.text())
      .then(text  => console.log(text))
    })

app/views/users/show.erb
hi
<% @user.id %>
<div class="user-pets-container">
  <div class='user-show' data-id=@user.id data-action='show-pet'>

  <h4>hi, <%= @user.name %></h4>
  <h4>hi, <%= @user.id %></h4>


  <h3>your pets</h3>





    <%= button_to 'adopt a pet', new_pet_path, method: :get, class: 'button' %><br><br>

    <%= button_to 'sign out', logout_path,  method: :get, data: { confirm: 'are u sure?' }, class: 'button' %><br><br>
    </div>
      </div>

app/views/users/show_park.erb
<div class="user-pets-container">

  <h4>hi, <%= @user.name %></h4>


  <h3>your pets</h3>

  <div id="my-pets">
    <ul>
    <li>  <% @user.pets.each do |pet|%>

      name: <%= button_to pet.name, pet_path(pet), method: :get, class: 'button'%>
      type of pet: <%= pet.kind%><br></li>


      <% end %>


    </ul>

    <%= button_to 'adopt a pet', new_pet_path, method: :get, class: 'button' %><br><br>

    <%= button_to 'sign out', logout_path,  method: :get, data: { confirm: 'are u sure?' }, class: 'button' %><br><br>
    </div>
    </div>